# \u670D\u52A1\u7AEF\u53E3
server:
  port: 8888

# \u6253\u5F00debug\u62A5\u544A\uFF0C\u65B9\u4FBF\u770B\u52A0\u8F7D\u60C5\u51B5
# debug: true

spring:
  datasource:
    # \u6570\u636E\u6E90
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-boot-01-atguigu-cache?useSSL=false&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    type: com.alibaba.druid.pool.DruidDataSource
    # \u6570\u636E\u6E90\u5176\u4ED6\u914D\u7F6E
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    # druid\u68C0\u6D4B\u914D\u7F6E
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

      # \u670D\u52A1\u542F\u52A8\u6267\u884Csql
      # schema:
      # - classpath:sql/department.sql
    # - classpath:sql/employee.sql
  # \u914D\u7F6Eredis\u8DEF\u5F84\u5730\u5740
  redis:
    host: localhost

mybatis:
  # mybatis\u914D\u7F6E\u6587\u4EF6
  # config-location: classpath:mybatis/mybatis-config.xml
  # mapper\u6620\u5C04\u6587\u4EF6
  mapper-locations: classpath:mybatis/mapper/*.xml

