spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-boot-01-atguigu-jpa?useSSL=false&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      # \u66F4\u65B0\u6216\u8005\u521B\u5EFA\u6570\u636E\u8868\u7ED3\u6784
      ddl-auto: update
      # \u63A7\u5236\u53F0\u663E\u793ASQL
      show-sql: true