server:
  port: 8888
  servlet:
    context-path: /shiro

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_shiro_baizhi?useSSL=false&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: root

  mvc:
    view:
      prefix: /
      suffix: .jsp

mybatis-plus:
  # 实体类路径配置
  typeAliasesPackage: com.baizhi.shiro.entity
  # mapper映射文件路径配置
  mapper-locations: classpath*:/mapper/*.xml
  # 打印日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl